### ISSUE TITLE
recaptcha verify_captcha returns SSL errors

### ISSUE THREAD

**Issue by XXChester** [ambethia/recaptcha#191] opened 2016-07-01 22:22 UTC
I have been fighting with a bug for the last day and half regarding this ssl error:
```SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed```

I have tried all of the suggestions on the web with regards to using incorrect root certs etc. Last night, I confirmed that the problem was with Ruby as I was able to curl and get a response from both Mac and a Windows command line with the following command (removed private key)
```
 curl --data "secret=MY-SECRET-KEY&response=03AHJ_VusxdYs5lb1FgubblUkXtndpmp5JeHAMNma7VU-mqXBRx-vAoP1Vob3zwZytX0Kg8KDPGf70is-T38ViRh5HuRj3FA7QTzfKDEvhUjkf15rgJGF28JLprjqAWPZhTMFdKxMHUtYtyklfQ9TtNRDTBZCt3SfbKO4879Q4Euvkg89oG7l2Livt_jBqdUbhrl_r488CM3wlErKWn155nBfI8XqQM_9bRWHqPDBVkZ3QFYH0rwRJXdbtPB71kw34N50vI67N-8laif2wkPhdmFqLnIJrCyC3untcAIXd-O5srfyvdXLL8ZiwqbzGb-Ms6gATzf0E8P9R0Oj7bmqyaQ4g3Tn7aV6XGucpRpf8gRfvc071x29DK6YDfCpwT19P7RL1p6pP8P7XUNCYPGJ9-9c7NXia4iG3ExorC6KbOBbLawVp6sNPIL2KX5H50BlAlRoPpm5GPoaTLnYZKgTY6Tl9NwtZuUF0E3T9hpPa_JeHqj4CC_8YBMymz58IpjxWcB6zamcoFZlb2KcJvzOIN55j28jgdLaAZohJRSTi2PeN_CCuX--L-PAmOR7BmdColhdkQUItXiGUaWfaG091r4tcEXxG6pElGCVK17RSRARbHFvvbqcxvbSXlwaScUAZbUDiTHAH2zmSHrZusi08hP3t3Ig5Qd-Bx17IccqipaklSpaRyos8Yp4vN4FnA0oVj6no--yAjdS4_Zfgg-tm4yZJRFUYUijeGMIYeacDishJEzrL_Gr5U01R-1U5xiO7Jcg_HozvJ2nHsKYdeNrD3xtD3L2w0E9UlooFaxGv8Gn94J6oCI7SHKjQOBoF5kXUohNwaCOrVp8fuO4nEoFhNxMgBAPZBlLDH013TOgws8moP4bZPbhgJ4gKsiJjPuqUJhcO7q5v7A9gmDDuoR2bWiuvy32rSNqtwjbk2VEoWTz1RvO0FcWKTRcGSYgshrXoDx1PEbOJ2j640qM8cVatyOLcx0CXBIDPHw" https://google.com/recaptcha/api/siteverify
```

Now that I knew the problem was internal to ruby, and not the whole OS, I loaded up a ruby project with this library and Curb. I have this piece of code:
```
def check_captcha
  https = Curl.get "https://google.com/recaptcha/api/siteverify?secret=" + Recaptcha.configuration.private_key +
  "&response=" + params["g-recaptcha-response"]
  puts https.body_str

  args = {"response" => params["g-recaptcha-response"], "secret" => Recaptcha.configuration.private_key}
  puts "ARGS:\n" + args.inspect.to_s
  unless verify_recaptcha args
    respond_with_navigational(resource) { render :new }
  end
end
```

When this piece of code is executed after a valid captcha entry, the first one utilizing Curl (ie. Curb) calls the API correctly and returns a result. The second call via your library however, throws the above SSL error.

Environment:
```
ruby -v:  2.2.0p0 (also 2.2.3)
gem -v: 2.4.6
rails: 4.2.6 (but exhibited on lower versions as well)
```

I am running a vanillar rails server without SSL.

Any help would be appreciated but none-the-less, now that I've identified the problem, I will use straight curl for the short-term.
Thanks,

**Comment by grosser** [comment] 2016-07-01 22:37
basically rubies ssl is messed up ... so using curl works because it has a different ssl ... not sure how to help with that / not a recaptcha specific issue :(

Set the environment variable SSL_CERT_FILE to the path of the PEM file that curl uses and it might work ... lots of google answers for that, so I'll not bother looking further ... 

closing since this is a ruby issue ... maybe complain to your ruby version manager provider or ops person of choice :D

**Closed by grosser** 2016-07-01 22:37 UTC

**Comment by XXChester** [comment] 2016-07-01 22:42
Just to clarify, setting the SSL_CERT_FILE didn't seem to help.

Why can it not be fixed in the library if there is a known work-around? Why leave it broken and unusable? I'd really like to use your library as it's clean, but what am I missing here?

**Comment by grosser** [comment] 2016-07-01 22:47
The issue is not the library, but that your local ruby is broken.
I don't know why it is broken ... making everyone use curl, because that works on your machine is not a viable workaround because:
 - it adds another heavy dependency on this project
 - it might fail on someone elses machine where curl is broken but ruby is not broken

Just because this library uses Net::Http and that is broken for you, does not mean we should add a workaround here, even if it was a small/innocent workaround.

**Comment by xampo848** [comment] 2016-07-08 16:20
@XXChester did you solve it? I get the same problem. but i find no way to fix it

**Comment by jetsekoopmans** [comment] 2016-07-12 11:16
Same here. Someone has a solution?

**Comment by ndesorden** [comment] 2016-07-28 07:18
Same problem. Solutions like https://gist.github.com/fnichol/867550 doesnt work :(

**Comment by XXChester** [comment] 2016-11-10 07:31
My solution while still on windows was to not use this library anymore and use raw curl which worked. But given the poor Ruby experience I Windows in general I ended up giving up a few weeks later and have been happily using Ubuntu ever since.

Once on Linux, this issue went away.

**Comment by grosser** [comment] 2016-11-10 07:47
🎉 the power of giving up :)

**Comment by rmagnum2002** [comment] 2017-03-25 06:56
Have the same issue on Mac, if this works on Linux why it wouldn't work on Mac?
Or should I give up as well? :)

**Comment by grosser** [comment] 2017-03-25 15:05
Yes, giving up is the answer ... but even if you find something, don't update this issue :trollface:
