### ISSUE TITLE
Uncaught Error: ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by trungnguyencmu** [ambethia/recaptcha#217] opened 2017-04-02 15:13 UTC
I got message on console: 'Uncaught Error: ReCAPTCHA placeholder element must be empty'
Please help me fix it
![screenshot 2017-04-02 22 12 56](https://cloud.githubusercontent.com/assets/8305733/24588409/94a3ec98-17f1-11e7-99df-a56f48f87b44.png)

Thanks!

**Comment by grosser** [comment] 2017-04-02 15:45
have not seen that before ... can you reproduce with the demo app ?

**Comment by trungnguyencmu** [comment] 2017-04-03 10:58
`= simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }, format: :json, :remote => true) do |f|
        = f.error_notification
        .form-inputs
          = f.input :email, label: false, required: false, autofocus: false, placeholder: "Email Address"
        .field-captcha
          = recaptcha_tags
        .action
          = f.submit "Login"
      .not-member
        span Back to
        span.button-modal.login-modal data='login-modal' Login`

this is a controller:
`def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?
    if verify_recaptcha
      flash.delete :recaptcha_error
      if successfully_sent?(resource)
        @success = true
      else
        @success = false
      end
    else
      @success = false
      resource.valid?
      resource.errors.add(:email, "There was an error with the recaptcha code below. Please re-enter the code.")
    end
    respond_to do |format|
      format.js do
        file = "users/passwords/forgot_password"
        render :file => file
      end
    end
  end`
I just implement on localhost, you can't reproduce this errors. @grosser

**Comment by trungnguyencmu** [comment] 2017-04-03 11:15
My Controller:
![screenshot 2017-04-03 18 13 17](https://cloud.githubusercontent.com/assets/8305733/24606864/55286ef6-1899-11e7-881d-0228c07a2393.png)

My View:
![screenshot 2017-04-03 18 13 31](https://cloud.githubusercontent.com/assets/8305733/24606869/60248196-1899-11e7-9e36-08c8e8bff203.png)

I'm doing on localhost, so I can reproduce for you ... Sorry @grosser 

Thanks!

**Comment by grosser** [comment] 2017-04-04 04:29
I meant, can you reproduce the error using the demo app that is in the
recaptcha repo ?

**Comment by designcitypl** [comment] 2017-04-12 01:32
@trungnguyencmu Are you using turbolinks in your app?

I had the same issue when page is cached by turbolinks and user is leaving this page (to another page, handled by turbolinks) and then _returns to_ the first page/view, where form with ReCAPTCHA is placed and has been rendered already (at first visit).

**Comment by Saidbek** [comment] 2017-04-28 11:48
I have the same error +1

**Comment by thaleshcv** [comment] 2017-05-10 12:37
same error +1 (same scenario described by @designcitypl )

**Comment by andyyou** [comment] 2017-05-24 06:36
Here is problem [example](https://github.com/andyyou/recaptcha/tree/master/demo/rails-v5)

I found out in rails 4 there is no problem, but in rails 5, if you visit `page` that has recaptcha first time, nothing happen, then you move to another page by click link and come back `page` error will show up

**Comment by grosser** [comment] 2017-05-24 14:34
any idea for a fix ... PR ?

**Comment by andyyou** [comment] 2017-06-20 08:45
I am not familiar with Ruby here is an idea after I read source code

```html
<div id="g-recaptcha-container"></div>
<script src="https://www.google.com/recaptcha/api.js?onload=recaptchaCallback&render=explicit" async defer></script>
<script>

function recaptchaCallback (e) {
  var container = document.getElementById('g-recaptcha-container')
  container.innerHTML = ''
  var recaptcha = document.createElement('div')
  grecaptcha.render(recaptcha, {
    'sitekey': '6LewZh8TAAAAAG3YT_c17GfHeOti25qrh9mK2fXa'
  })
  container.appendChild(recaptcha)
}
</script>
```

**Comment by grosser** [comment] 2017-06-20 16:18
can you turn that into a PR and link this here so the other users with the same issue can review ?

**Comment by jvopelak** [comment] 2017-08-08 15:23
same error +1

**Comment by dimanlin** [comment] 2017-09-03 21:26
I's hapend if i have two "recaptcha_tags" on the page.
+1

**Comment by grosser** [comment] 2017-09-03 22:22
might also be able to set a `@script_tag_already_renderd` ... and then don't render it twice

**Comment by farhad-tarapore** [comment] 2017-09-11 12:12
Is there any solution for this? I'm using <%= recaptcha_tags %> in ruby view file and I'm getting the same error

**Comment by Rahul-Sagore** [comment] 2017-09-11 13:35
When you use `recapthca_tag`, it loads script library by default every time it renders.
You have to pass:`script => false` to stop injecting of script again and again.
`<%= recaptcha_tag :script => false %>`

**Comment by trungnguyencmu** [comment] 2017-09-11 13:37
recaptcha load twice in my app, check carefully ... 🗡

**Comment by alexismansilla** [comment] 2017-12-19 19:00
Recaptcha load twice in your app 🍟

**Comment by damonbakker** [comment] 2018-06-20 10:06
I got the same error but not because of having two tags on one page.

My issue was similar to what @designcitypl described. My pages are cached, so the placeholder wasn't empty when the cached version was being shown.

I solved it by emptying the g-recpatcha element before the pages get cached by turbolinks.

```
document.addEventListener("turbolinks:before-cache", function() {
   $('.g-recaptcha').empty();
});
```

Note that I am using jquery, you probably don't have to for this.

**Comment by jean-francois-labbe** [comment] 2019-03-08 10:20
I had the same issue, you can also opt-out of turbolinks cache for this page: https://github.com/turbolinks/turbolinks#opting-out-of-caching

you just need to add a meta to the page:
```html
<head>
  ...
  <meta name="turbolinks-cache-control" content="no-cache">
</head>
```

**Comment by coisnepe** [comment] 2020-04-17 12:40
Had the same issue. Solved thanks to @damonbakker !

Note that [You Might Not Need jQuery™](http://youmightnotneedjquery.com/)

```javascript
document.addEventListener("turbolinks:before-cache", function () {
  document.querySelector(".g-recaptcha").innerHTML = "";
});
```

**Comment by grosser** [comment] 2020-04-17 15:34
I'll close this now since there are a few solutions already ... if anyone has an idea how to turn that into a PR do! :)

**Closed by grosser** 2020-04-17 15:34 UTC

**Comment by jean-francois-labbe** [comment] 2023-09-27 14:08
With hotwire now, you can opt-out of cache with a data attribute.

> **data-turbo-temporary** removes the element before the document is cached, preventing it from reappearing when restored.

https://turbo.hotwired.dev/reference/attributes

```erb
<%= turbo_frame_tag 'recaptchas', data: { turbo_temporary: true } do %>
  <%= recaptcha_v3(action: 'login', site_key: 'key', turbolinks: true) %>
<% end %>
```
